name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  lint:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    uses: community-of-python/community-workflow/.github/workflows/lint.yml@main
    with:
      python-version: '["3.10","3.11","3.12","3.13","3.14"]'
    secrets: inherit

  test:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    uses: community-of-python/community-workflow/.github/workflows/test.yml@main
    with:
      python-version: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
      os: '["ubuntu-latest", "macos-latest", "windows-latest"]'
    secrets: inherit

  publish:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    uses: community-of-python/community-workflow/.github/workflows/publish.yml@main
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
