name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  lint:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    uses: community-of-python/community-workflow/.github/workflows/lint.yml@main
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  test:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    uses: community-of-python/community-workflow/.github/workflows/test.yml@main
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit

  publish:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    uses: community-of-python/community-workflow/.github/workflows/publish.yml@main
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
